name: Deploy
on:
  push:
    branches:
      - main
jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: version
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            node --print 'require("./lerna.json").version'
  npm-package:
    runs-on: ubuntu-latest
    needs: update-version
    if: ${{ needs.update-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - run: yarn --immutable --immutable-cache
      - run: yarn build
      - run: echo //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN} > .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn lerna publish from-package --yes
