name: Storybook
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '274.0.0'
          service_account_key: ${{ secrets.GCP_KEY }}
      - run: yarn
      - run: yarn build-demo
        env:
          TITLE: ${{ github.head_ref }}
      - run: yarn deploy-demo
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          COMMIT: ${{ github.sha }}
          REF: ${{ github.head_ref }}
